id: cb16d8513dc3409d9b0d8b1c051d2949
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_11-The_Transcendent_Perfection_of_Wisdom_in_Ten_Thousand_Lines-v1
  language: bo
  author: ''
  volume: {}
